// Datos de la línea del tiempo - 24 hitos para nuestro primer año
const timelineData = [
  {
    id: 1,
    date: "07 de marzo, 2024",
    title: "Nuestro primer contacto",
    icon: "fa-brands fa-facebook-f", // Icono de Font Awesome
    content: {
      text: "El primer 'Hola' luego del match en la app de caradelibro. Ilusionado por un nuevo tipo de ortopedia vendida por una misteriosa mujer",
      images: ["images/primermsjeface.jpg", "images/primermsjeface2.jpg"],
      audio: "audio/PF - Mi Forma De Sentir.mp3",
      emoji: "👀",
    },
    type: "love", // Puedes usar tipos para categorizar eventos
  },
  {
    id: 2,
    date: "10 de marzo, 2024",
    title: "El primer WhatsApp",
    icon: "fa-brands fa-whatsapp",
    content: {
      text: "8 minutos después del último mensaje en Facebook, el primer mensaje de WhatsApp. Aún preguntando por características y descuentos.",
      images: ["images/primermsjewsp.jpg"],
      emoji: "📱",
      audio: "audio/Manuel Turizo - Quiéreme Mientras Se Pueda.mp3",
    },
    type: "date",
  },
  {
    id: 3,
    date: "13 de marzo, 2024",
    title: "It's a deal",
    icon: "fa-solid fa-handshake",
    content: {
      text: "Yo no lo tenía pensado, pero a los 3 días de hablar por WhatsApp mi subconciente ya había decidido que quería conocerte, y se expresó... en inglés el pretencioso.",
      images: ["images/itsadeal.jpg"],
      audio: "audio/Embrace - Gravity.mp3",
      emoji: "😱",
    },
    type: "trip",
  },
  {
    id: 4,
    date: "28 de marzo, 2024",
    title: "Momento de conocerse",
    icon: "fa-solid fa-face-rolling-eyes",
    content: {
      text: "Llegó el momento. Salí sin expectativas y sin pato, pero con la secreta esperanza de que todo saliera bien y de que ese no fuera el final, si no el punto de partida de lo que sea... y así fue. Reconocí a la hermosa mujer de mi vida. Y así fue.",
      images: ["images/primerajunta.jpg", "images/primerajunta2.jpg"],
      audio: "audio/Roberto Carlos ft Jennifer Lopez - Llegaste.mp3",
      emoji: "😍",
    },
    type: "date",
  },
  {
    id: 5,
    date: "06 de Abril, 2024",
    title: "El primer beso",
    icon: "fas fa-kiss-wink-heart",
    content: {
      text: "La primera vez en mi casa, Gaby hermosa y perfecta, una película que nadie recuerda, escenario tranquilo e ideal, primer beso. Soñado, pero jamás esperado. Dejó huella en mí y en mi corazón y, lamentablemente, otras huellas.",
      images: ["images/beso.jpg", "images/beso2.jpg"],
      audio: "audio/Ed Sheeran - Perfect.mp3",
      emoji: "💋",
    },
    type: "love",
  },
  {
    id: 6,
    date: "08 de Abril, 2024",
    title: "Hola",
    icon: "fa-solid fa-headphones-simple",
    content: {
      text: "Surge la idea de crear una playlist para nosotros. Con un nombre carente de ingenio, con tropiezos al principio, termina siendo un pilar fundamental para declarar y asimilar sensaciones. Y hasta el nombre fue reivindicado. Sigue en construcción...",
      images: ["images/playlist.JPG", "images/playlist2.jpg"],
      audio: "audio/Río Roma - Me Cambiaste la Vida.mp3",
      emoji: "🎶",
    },
    type: "anniversary",
  },
  {
    id: 7,
    date: "14 de Abril, 2024",
    title: "Nos vemos por videollamada",
    icon: "fas fa-video",
    content: {
      text: "Aunque ya habíamos hablado de la opción de videollamada, no lo habíamos hecho. Ese día, mientras jugaban los niños y sentada en el círculo se hizo la primera. Terminó siendo una de las instancias que más espero en mi día a día. Ver su sonrisa, sus ojitos, y escuchar su voz... Me encanta!.",
      images: ["images/primeravideoll.jpg", "images/primeravideollnoche.jpg"],
      audio: "audio/Luis Fonsi - Aqui Estoy Yo.mp3",
      emoji: "📲",
    },
    type: "date",
  },
  {
    id: 8,
    date: "14 de abril, 2024",
    title: "Evidencias",
    icon: "fa-solid fa-face-flushed",
    content: {
      text: "El día de 'Evidencias', a pesar del impas, algo se evidenció. Había esperanzas que salieron a flote en la conversación posterior y fue un punto de inflexión. Evidencias terminó teniendo su segunda oportunidad la noche del 16-17 de mayo, luego de decidir hablar con sus padres... pero ese es otro hito",
      images: ["images/evidencias.jpg", "images/evidencias2.jpg"],
      audio: "audio/Ana Gabriel - Evidencias.mp3",
      emoji: "🎵",
    },
    type: "home",
  },
  {
    id: 9,
    date: "20 de abril, 2024",
    title: "Primera noche juntos",
    icon: "fa-solid fa-star",
    content: {
      text: "Nuestra primera noche juntos no se produjo, no hubo ningún plan cuidadosamente elaborado. La realidad es que esa noche estuvo donde la amiga Danny, lugar al que se fue después de que el equipo de Antartica (mi favorito) ganara todos sus partidos. No hay fotos de esa noche, solo una de algunos presentes que su amiga le dió sin motivo aparente.",
      images: ["images/primeranoche.jpg"],
      audio: "audio/Snow Patrol - Chasing Cars.mp3",
      emoji: "😈",
    },
    type: "home",
  },
  {
    id: 10,
    date: "29 de abril, 2024",
    title: "Lunes histórico",
    icon: "fas fa-bolt",
    content: {
      text: "Ese lunes fue especial. Junto a lo que disfrutamos fue sentirse vivo, un poco loco, sentir que el corazón, hace un tiempo apagado, estaba ahora encendido y se arrancaba del pecho. Fue también saber que estábamos en cierta sintonía, pensar que tal vez y solo tal vez, si nos proponíamos lograr algo, lo que sea, podíamos hacerlo suceder. Fue un lunes mágico.",
      images: ["images/lunes.jpg", "images/lunes2.jpg", "images/lunes3.jpg"],
      audio: "audio/Reyli - Amor del Bueno.mp3",
      emoji: "😋",
    },
    type: "love",
  },
  {
    id: 11,
    date: "04 de mayo, 2024",
    title: "Noche impensada",
    icon: "fa-solid fa-face-grin-stars",
    content: {
      text: "Un momento de felicidad como pocos hasta ese momento de la vida. Pasar de la resignación por no estar contigo esa noche a la posibilidad de que te quedaras casi me hace caminar y saltar de alegría. Luego, una sesión de fotos en que pude hacer gala de mis dotes fotogénicos.",
      images: [
        "images/impensada.jpg",
        "images/impensada2.jpg",
        "images/impensada4.jpg",
      ],
      audio: "audio/Carla Morrison - Eres tú.mp3",
      emoji: "🤗",
    },
    type: "celebration",
  },
  {
    id: 12,
    date: "16 de mayo, 2024",
    title: "Hablando con los padres",
    icon: "fa-solid fa-person-walking-arrow-right",
    content: {
      text: "Si de momentos importantes se habla, este es uno en el podio. Era algo que venía esperando hace un rato, la confirmación de algo, el paso hacia adelante que sabía que querías dar, pero no te atrevías porque tus miedos no te dejaban ver lo valiente que eres... y, aunque los miedos estaban ahí todavía, lo hiciste. Valentía pura. Sorpresa y emoción de mi parte y el amor ya tenía su lugar.",
      images: ["images/papas.jpg"],
      audio: "audio/La Quinta Estación - Algo Más.mp3",
      emoji: "🔥",
    },
    type: "love",
  },
  {
    id: 13,
    date: "18 de mayo, 2024",
    title: "Compromiso",
    icon: "fa-solid fa-hand-holding-heart",
    content: {
      text: "Llegó el sábado. Ese día pudo venirse después de las 18 hrs, eran tiempos distintos. No recuerdo si fue antes o después del sushi (imagino que fue después xd) se dió la conversación más maravillosa del mundo mundial. En un koala cargado de sensaciones, se hacía realidad el sueño de las reevaluaciones y se materializaba todo lo bonito que vivíamos en AMOR ♥. El comienzo del siguiente nivel en nuestra historia.",
      images: ["images/compromiso.jpg", "images/compromiso2.jpg"],
      audio: "audio/Whitney Houston - I Have Nothing.mp3",
      emoji: "💕",
    },
    type: "love",
  },
  {
    id: 14,
    date: "06 de Junio, 2024",
    title: "Cumple Pedri",
    icon: "fas fa-birthday-cake",
    content: {
      text: "Llegó el día en que la tierra había dado 44 vueltas alrededor del sol desde que nací. Nada muy especial hasta ese año, pero este fue diferente. Tenía el corazón llenito y estar con una mujer maravillosa como tú lo hacía especial. Me lo hizo notar desde el principio, su saludo, sus sorpresas, los detalles.... y el mejor ragalo: tenerla en mi vida.",
      images: [
        "images/cumpleyo3.jpg",
        "images/cumpleyo.jpg",
        "images/cumpleyo2.jpg",
      ],
      audio: "audio/Carla Morrison Te Regalo.mp3",
      emoji: "🎉",
    },
    type: "celebration",
  },
  {
    id: 15,
    date: "26 de julio, 2024",
    title: "Conocer a los niños",
    icon: "fa-solid fa-children",
    content: {
      text: "Un check importante era conocer a los niños. Esperaba hacerlo en un momento y lugar casual, como ir por la calle y '¡oh! qué sorpresa', pero no, hubo tiempo previo para pensar en cómo les iba a dar la mano xd. Más allá de eso, sí fue un momento relajado y se dió de la mejor manera. Sin apretones de manos, pero de la mejor manera.",
      images: ["images/conocerninos.jpg", "images/conocerninos2.jpg"],
      audio: "audio/Reik - Creo en Ti.mp3",
      emoji: "😎",
    },
    type: "achievement",
  },
  {
    id: 16,
    date: "31 de julio, 2024",
    title: "Cumple de Gaby",
    icon: "fas fa-birthday-cake",
    content: {
      text: "Un día especial porque cumplía un año más mi amorcito. Un día para agradecer su existencia y el hecho de tenerla en mi vida. Un día para reflexionar también en la responsabilidad de cuidarla y de hacer todo lo que esté en mis manos para que este año más sea bueno y lo disfrute.... y así, todos los años.",
      images: [
        "images/cumplegaby2.jpg",
        "images/cumplegaby3.jpg",
        "images/cumplegaby.jpg",
      ],
      audio: "audio/Sin Bandera - Que Me Alcance La Vida.mp3",
      emoji: "🎊",
    },
    type: "celebration",
  },
  {
    id: 17,
    date: "18 de septiembre, 2024",
    title: "Tiki tiki ti",
    icon: "fa-solid fa-utensils",
    content: {
      text: "El primer asado con parrilla electrica. Carne blandita, anticuchos espectaculares, terremotos exquisitos... pero aparte de comer rico y en abundancia, lo mejor fue que ese fin de semana largo lo pasamos acá. Primera vez que estuvimos tanto tiempo juntos. Y fue genial.",
      images: ["images/18sept2.jpg", "images/18sept3.jpg", "images/18sept.jpg"],
      audio: "audio/Ha-Ash Feat. Prince Royce - 100 Años.mp3",
      emoji: "🍢",
    },
    type: "celebration",
  },
  {
    id: 18,
    date: "16 de noviembre, 2024",
    title: "Conociendo al suegri",
    icon: "fa-solid fa-face-grin-beam-sweat",
    content: {
      text: "Otro check importante, conocer al suegri. Tampoco se dio lo de ir por Macul un día y '¡oh! qué sorpresa', sin embargo, fue un momento relajado, sin pretenciiones de presentación formal ni etiquetas. Claro, no era necesario, pero suele estar esa idea al conocer al suegri. Un check que se dio naturalmente. Aunque aún faltaba....",
      images: ["images/conocerpapa.jpg"],
      audio: "audio/Kany García - Perfecto para Mi.mp3",
      emoji: "😊",
    },
    type: "achievement",
  },
  {
    id: 19,
    date: "25 de diciembre, 2024",
    title: "Navidad juntos",
    icon: "fas fa-snowflake",
    content: {
      text: "Otra celebración un tanto ajena para mi hasta ese entonces. No tenía mayores expectativas, hasta que me dijo que había hecho los arreglos para pasarla conmigo. Saber que había decidido pasar una fecha importante para usted conmigo fue sorpresivo a la vez que emocionante. Adornar un arbolito nunca fue una aventura tan motivante como lo fue ahora para celebrar con mi Gaby.",
      images: [
        "images/navidad.jpg",
        "images/navidad2.jpg",
        "images/navidad3.jpg",
        "images/navidad4.jpg",
      ],
      audio: "audio/Mario Guerrero - Te Amaré.mp3",
      emoji: "🎄",
    },
    type: "celebration",
  },
  {
    id: 20,
    date: "14 de febrero, 2025",
    title: "San Valentín",
    icon: "fa -solid fa-heart",
    content: {
      text: "San Valentín no era una fecha que me emocionara (otra más, si lo sé, soy medio amargo), pero este año fue diferente. Ya no era un 'día comercial', era el día del amor, y llegaba conmigo enamorado. Ahora había razón para celebrar, tenía significado. La idea de pasar un día especial con mi amorcito, de compartir unas papitas mechadas con la mujer de mi vida celebrando el amor... dame ese panorama mil veces diosito. Y mi nuevo tazón... y los koalas de lana..... grande San Valentín!!",
      images: [
        "images/valentin.jpg",
        "images/valentin2.jpg",
        "images/valentin3.jpg",
      ],
      audio: "audio/Adele - Make You Feel My Love.mp3",
      emoji: "💖",
    },
    type: "celebration",
  },
  {
    id: 21,
    date: "23 de febrero, 2025",
    title: "Conociendo a la suegri",
    icon: "fa-solid fa-face-grin-beam-sweat",
    content: {
      text: "Había pasado un tiempo desde que conocí a su papá, y ya era hora de conocer a su mamá. Era un check pendiente con cierta tensión en su núcleo, ni tanta, pero sí tenía un 'uuuuuuuuuh' que lo acompañaba... uuuuuh. Nunca sabremos lo que pensó en su interior al conocer al mooonstruooo, lo que sí sabemos es que hubo un pastel de choclo exquisito y que fue una tarde tranquila y agradable. También se dio todo muy natural, sin formalidades y fluyó. Ahora la suegri me hace pantrucas... me atrevería a decir que está todo bien y que los check familiares han sido un éxito. Aunque faltaba uno.",
      images: ["images/conocermama.jpg"],
      audio: "audio/Extreme - More Than Words.mp3",
      emoji: "😊",
    },
    type: "achievement",
  },
  {
    id: 22,
    date: "16 de marzo, 2025",
    title: "Agustina y la cruda verdad",
    icon: "fa-solid fa-child-dress",
    content: {
      text: "Bueno no tan cruda, de hecho, para nada cruda. Se dio todo de una manera que le resultó fácil de entender y asimilar. Incluso hasta en sus términos, descubriendo quién era (nunca olvidaré que fui como la décima opción), haciendo gancho para que que pololiáramos y buscando opciones y estratégias para declararme. En el fondo no lo habría logrado sin ella xd. Otro check importante aprobado.",
      images: ["images/agus.jpg"],
      audio: "audio/Ilan Chester - Un querer como el tuyo.mp3",
      emoji: "😄",
    },
    type: "achievement",
  },
  {
    id: 23,
    date: "18 de abril, 2025",
    title: "Conociendo a mi familia",
    icon: "fa-solid fa-users",
    content: {
      text: "Bueno, luego de ir conociendo a sus cientos de familiares, llegó el momento de que conociera a la docena de los míos. Ya había compartido con mi tía y faltaba el resto. Que mejor que en semana santa, llenos de espiritualidad... y llenos de comida. Pedro feliz, familia feliz por Pedro feliz y mi Gaby es una más de la familia... feliz.",
      images: [
        "images/conocerfamilia1.jpg",
        "images/conocerfamilia.jpg",
        "images/conocerfamilia2.jpg",
      ],
      audio: "audio/Bryan Adams - (Everything I Do) I Do It For You.mp3",
      emoji: "🍲",
    },
    type: "achievement",
  },
  {
    id: 24,
    date: "01 de mayo, 2025",
    title: "Cumple de Martín y conociendo a hermanos",
    icon: "fa-solid fa-people-group",
    content: {
      text: "Por último, el último check familiar: conocer a los hermanos de Gaby. Un momento que no estaba en los planes próximos, pero que tenía que pasar. Y fue gracias a la invitación de Martín a su cumple. Un evento masivo, lleno de adolescentes y donde estaría la crème de la crème del entorno de mi Gaby. '¡Qué susto!', podría decir alguien... y sí, casi muero. Nah, todo bien, todo tranquilo, fluyó de buena manera, creo. Otro hito natural y fluido.",
      images: ["images/cumplemartin.jpg"],
      audio: "audio/JESSE & JOY, Luis Fonsi - Tanto.mp3",
      emoji: "🎂",
    },
    type: "celebration",
  },
  {
    id: 25,
    date: "18 de mayo, 2025",
    title: "Aniversario",
    icon: "fa-solid fa-heart",
    content: {
      text: "Y así ha llegado nuestro primer aniversario. Siempre que hago recuentos mentales de lo nuestro, verá que empiezo el 7 de marzo y lo hice así incluso ahora en que celebramos un año desde el 18 de mayo de 2024. Lo dije una vez y creo que este es momento de repetirlo, de nuevo, otra vez: atesoro y aprecio lo que he vivido desde el momento de conocerla, desde la primera letra que se escribió en el chat y hasta de ese mach que nos hizo encontrarnos. En ese entonces, no lo sabía, ni lo soñaba y en mi escepticismo tampoco lo creía posible... no imaginaba que un 18 de mayo de 2025 estaría feliz y enamorado de esa mujer maravillosa que no desistió. De la mujer que me hizo volver a sentir, que despertó mi corazón de su letargo y le dio nueva vida. De esa mujer valiente que enfrentó sus miedos y se atrevió. De aquella mujer inteligente y hermosa que puede lograr lo que se propone y ha elegido estar conmigo, hacerme parte de su vida y darme felicidad. De la mujer que amo con mi vida. De la persona con quién espero pasar el resto de la vida amándola, cuidádola, marcando nuevos hitos, marcando nuevos checks, celebrando nuevos aniversarios hasta viejitos. De mi amorcito, de mi Gaby. Te amo infinito.",
      images: ["images/aniversario.jpg"],
      audio: "audio/Lady Gaga, Bruno Mars - Die With A Smile.mp3",
      emoji: "💞❣💖",
    },
    type: "celebration",
  },
];

// Mapeo de tipos de eventos con colores
const typeColors = {
  love: "#ff7b9c",
  date: "#ff9a7b",
  trip: "#7bc9ff",
  family: "#7bff9a",
  entertainment: "#c97bff",
  anniversary: "#ffda7b",
  home: "#7bd5ff",
  celebration: "#ffaa55",
  achievement: "#55c7ff",
  spontaneous: "#d67bff",
  symbolic: "#97db5e",
};

// Exportar los datos para que puedan ser importados desde app2.js
export { timelineData, typeColors };
