// Datos de la línea del tiempo - 24 hitos para nuestro primer año
const timelineData = [
  {
    id: 1,
    date: "07 de marzo, 2024",
    title: "Nuestro primer contacto",
    icon: "fa-brands fa-facebook-f", // Icono de Font Awesome
    content: {
      text: "El primer 'Hola' luego del match en la app de caradelibro. Ilusionado por un nuevo tipo de ortopedia vendida por una misteriosa mujer",
      images: ["images/primermsjeface.jpg", "images/primermsjeface2.jpg"],
      audio: "audio/PF - Mi Forma De Sentir.mp3",
      emoji: "👀",
    },
    type: "love", // Puedes usar tipos para categorizar eventos
  },
  {
    id: 2,
    date: "10 de marzo, 2024",
    title: "El primer WhatsApp",
    icon: "fa-brands fa-whatsapp",
    content: {
      text: "8 minutos después del último mensaje en Facebook, el primer mensaje de WhatsApp. Aún preguntando por características y descuentos.",
      images: ["images/primermsjewsp.jpg"],
      emoji: "📱",
      audio: "audio/Manuel Turizo - Quiéreme Mientras Se Pueda.mp3",
    },
    type: "date",
  },
  {
    id: 3,
    date: "13 de marzo, 2024",
    title: "It's a deal",
    icon: "fa-solid fa-handshake",
    content: {
      text: "Yo no lo tenía pensado, pero a los 3 días de hablar por WhatsApp mi subconciente ya había decidido que quería conocerte, y se expresó... en inglés el pretencioso.",
      images: ["images/itsadeal.jpg"],
      audio: "audio/Embrace - Gravity.mp3",
      emoji: "😱",
    },
    type: "trip",
  },
  {
    id: 4,
    date: "28 de marzo, 2024",
    title: "Momento de conocerse",
    icon: "fa-solid fa-face-rolling-eyes",
    content: {
      text: "Llegó el momento. Salí sin expectativas y sin pato, pero con la secreta esperanza de que todo saliera bien y de que ese no fuera el final, si no el punto de partida de lo que sea... y así fue. Reconocí a la hermosa mujer de mi vida. Y así fue.",
      images: ["images/primerajunta.jpg", "images/primerajunta2.jpg"],
      audio: "audio/Roberto Carlos ft Jennifer Lopez - Llegaste.mp3",
      emoji: "😍",
    },
    type: "date",
  },
  {
    id: 5,
    date: "06 de Abril, 2024",
    title: "El primer beso",
    icon: "fas fa-kiss-wink-heart",
    content: {
      text: "La primera vez en mi casa, Gaby hermosa y perfecta, una película que nadie recuerda, escenario tranquilo e ideal, primer beso. Soñado, pero jamás esperado. Dejó huella en mí y en mi corazón y, lamentablemente, otras huellas.",
      images: ["images/beso.jpg", "images/beso2.jpg"],
      audio: "audio/Ed Sheeran - Perfect2.mp3",
      emoji: "💋",
    },
    type: "love",
  },
  {
    id: 6,
    date: "08 de Abril, 2024",
    title: "Hola",
    icon: "fa-solid fa-headphones-simple",
    content: {
      text: "Surge la idea de crear una playlist para nosotros. Con un nombre carente de ingenio, con tropiezos al principio, termina siendo un pilar fundamental para declarar y asimilar sensaciones. Y hasta el nombre fue reivindicado. Sigue en construcción...",
      images: ["images/playlist.JPG", "images/playlist2.jpg"],
      audio: "audio/Río Roma - Me Cambiaste la Vida.mp3",
      emoji: "🎶",
    },
    type: "anniversary",
  },
  {
    id: 7,
    date: "14 de Abril, 2024",
    title: "Nos vemos por videollamada",
    icon: "fas fa-video",
    content: {
      text: "Aunque ya habíamos hablado de la opción de videollamada, no lo habíamos hecho. Ese día, mientras jugaban los niños y sentada en el círculo se hizo la primera. Terminó siendo una de las instancias que más espero en mi día a día. Ver su sonrisa, sus ojitos, y escuchar su voz... Me encanta!.",
      images: ["images/primeravideoll.jpg", "images/primeravideollnoche.jpg"],
      audio: "audio/Ha-Ash Feat. Prince Royce - 100 Años.mp3",
      emoji: "📲",
    },
    type: "date",
  },
  {
    id: 8,
    date: "14 de abril, 2024",
    title: "Evidencias",
    icon: "fa-solid fa-face-flushed",
    content: {
      text: "El día de 'Evidencias', a pesar del impas, algo se evidenció. Había esperanzas que salieron a flote en la conversación posterior y fue un punto de inflexión. Evidencias terminó teniendo su segunda oportunidad la noche del 16-17 de mayo, luego de decidir hablar con sus padres... pero ese es otro hito",
      images: ["images/evidencias.jpg", "images/evidencias2.jpg"],
      audio: "audio/Ana Gabriel - Evidencias.mp3",
      emoji: "🎵",
    },
    type: "home",
  },
  {
    id: 9,
    date: "20 de abril, 2024",
    title: "Primera noche juntos",
    icon: "fa-solid fa-star",
    content: {
      text: "Nuestra primera noche juntos no se produjo, no hubo ningún plan cuidadosamente elaborado. La realidad es que esa noche estuvo donde la amiga Danny, lugar al que se fue después de que el equipo de Antartica (mi favorito) ganara todos sus partidos. No hay fotos de esa noche, solo una de algunos presentes que su amiga le dió sin motivo aparente.",
      images: ["images/primeranoche.jpg"],
      audio: "audio/Snow Patrol - Chasing Cars.mp3",
      emoji: "😈",
    },
    type: "home",
  },
  {
    id: 10,
    date: "29 de abril, 2024",
    title: "Lunes histórico",
    icon: "fas fa-bolt",
    content: {
      text: "Ese lunes fue especial. Junto a lo que disfrutamos fue sentirse vivo, un poco loco, sentir que el corazón, hace un tiempo apagado, estaba ahora encendido y se arrancaba del pecho. Fue también saber que estábamos en cierta sintonía, pensar que tal vez y solo tal vez, si nos proponíamos lograr algo, lo que sea, podíamos hacerlo suceder. Fue un lunes mágico.",
      images: ["images/lunes.jpg", "images/lunes2.jpg", "images/lunes3.jpg"],
      audio: "audio/Reyli - Amor del Bueno.mp3",
      emoji: "😋",
    },
    type: "love",
  },
  {
    id: 11,
    date: "28 de Octubre, 2024",
    title: "Halloween juntos",
    icon: "fas fa-ghost",
    content: {
      text: "Nuestros disfraces combinados para Halloween fueron la sensación. Todos nos pedían fotos y no podíamos parar de reír por las reacciones. Planear y crear esos disfraces juntos fue casi tan divertido como usarlos.",
      images: ["images/halloween.jpg", "images/halloween-2.jpg"],
      emoji: "🎃",
    },
    type: "celebration",
  },
  {
    id: 12,
    date: "10 de Noviembre, 2024",
    title: "La primera vez que dijimos 'te amo'",
    icon: "fas fa-heart",
    content: {
      text: "Ese momento tan especial cuando por primera vez nos dijimos 'te amo'. No estaba planeado, simplemente sucedió naturalmente. El brillo en tus ojos y cómo se aceleró mi corazón es algo que nunca olvidaré.",
      images: ["images/love.jpg"],
      audio: "audio/special-moment.mp3",
      emoji: "💘",
    },
    type: "love",
  },
  {
    id: 13,
    date: "25 de Noviembre, 2024",
    title: "Nuestro primer Thanksgiving",
    icon: "fas fa-drumstick-bite",
    content: {
      text: "Celebrar Thanksgiving juntos y con nuestras familias fue un paso importante. Ver cómo todos se llevaban tan bien me hizo pensar en el futuro y en todas las festividades que vendrán.",
      images: ["images/thanksgiving.jpg"],
      emoji: "🦃",
    },
    type: "celebration",
  },
  {
    id: 14,
    date: "12 de Diciembre, 2024",
    title: "Escapada de fin de semana",
    icon: "fas fa-compass",
    content: {
      text: "Ese fin de semana espontáneo en la cabaña en las montañas. Sin internet, solo nosotros, la naturaleza, largas caminatas y noches frente a la chimenea. A veces necesitamos desconectar para conectar más profundamente.",
      images: ["images/cabin.jpg", "images/cabin-2.jpg"],
      emoji: "🏔️",
    },
    type: "trip",
  },
  {
    id: 15,
    date: "24 de Diciembre, 2024",
    title: "Nuestra primera Navidad",
    icon: "fas fa-gifts",
    content: {
      text: "Nuestra primera Navidad juntos fue mágica. Decorar el árbol, intercambiar regalos, esa cena especial que preparamos... Comenzar nuestras propias tradiciones navideñas es algo que siempre atesoraré.",
      images: ["images/christmas.jpg", "images/christmas-gifts.jpg"],
      audio: "audio/christmas-song.mp3",
      emoji: "🎄",
    },
    type: "celebration",
  },
  {
    id: 16,
    date: "31 de Diciembre, 2024",
    title: "Año Nuevo y nuevas promesas",
    icon: "fas fa-glass-cheers",
    content: {
      text: "Recibir el Año Nuevo juntos, mirando los fuegos artificiales, brindando por todo lo vivido y por lo que vendrá. Las promesas que nos hicimos esa noche son el cimiento de nuestro futuro juntos.",
      images: ["images/new-year.jpg"],
      emoji: "🎆",
    },
    type: "celebration",
  },
  {
    id: 17,
    date: "15 de Enero, 2025",
    title: "Nuestro proyecto conjunto",
    icon: "fas fa-paint-brush",
    content: {
      text: "Cuando empezamos ese proyecto creativo juntos no sabíamos en qué terminaría. Ver cómo combinamos nuestras habilidades y creamos algo único fue muy satisfactorio. Somos un gran equipo.",
      images: ["images/project.jpg"],
      emoji: "🎨",
    },
    type: "achievement",
  },
  {
    id: 18,
    date: "14 de Febrero, 2025",
    title: "Nuestro primer San Valentín",
    icon: "fas fa-dove",
    content: {
      text: "San Valentín siempre parecía comercial hasta que lo celebré contigo. Esa cena especial, el paseo bajo las estrellas, los pequeños detalles durante todo el día... Me hiciste creer en la magia de esta fecha.",
      images: ["images/valentine.jpg"],
      audio: "audio/romantic-song.mp3",
      emoji: "💝",
    },
    type: "celebration",
  },
  {
    id: 19,
    date: "05 de Marzo, 2025",
    title: "La gran noticia",
    icon: "fas fa-award",
    content: {
      text: "Cuando recibiste esa gran noticia y yo fui la primera persona a quien llamaste para compartirla. Tu emoción, tus lágrimas de felicidad, poder celebrar juntos ese logro tan importante para ti... me sentí tan orgulloso.",
      images: ["images/celebration.jpg"],
      emoji: "🏆",
    },
    type: "achievement",
  },
  {
    id: 20,
    date: "20 de Marzo, 2025",
    title: "Nuestro baile bajo la lluvia",
    icon: "fas fa-cloud-rain",
    content: {
      text: "Ese día que nos atrapó la lluvia en el parque y en lugar de correr, me tomaste de la mano y empezamos a bailar. Empapados, riendo, viviendo plenamente ese momento inesperado. Así es como quiero vivir contigo, abrazando cada sorpresa.",
      images: ["images/rain-dance.jpg"],
      emoji: "💃",
    },
    type: "spontaneous",
  },
  {
    id: 21,
    date: "10 de Abril, 2025",
    title: "Día de voluntariado juntos",
    icon: "fas fa-hands-helping",
    content: {
      text: "El día que fuimos voluntarios en ese refugio me mostró otra faceta tuya que me enamoró aún más. Tu generosidad, empatía y esa capacidad de conectar con todos... Me inspiraste a ser mejor persona.",
      images: ["images/volunteer.jpg"],
      emoji: "🤝",
    },
    type: "achievement",
  },
  {
    id: 22,
    date: "22 de Abril, 2025",
    title: "Nuestra promesa",
    icon: "fas fa-ring",
    content: {
      text: "La noche que intercambiamos esas promesas y los anillos que simbolizan nuestro compromiso de estar siempre el uno para el otro. No necesitábamos una ocasión especial, simplemente sentimos que era el momento perfecto.",
      images: ["images/promise.jpg"],
      audio: "audio/promise-song.mp3",
      emoji: "💍",
    },
    type: "love",
  },
  {
    id: 23,
    date: "01 de Mayo, 2025",
    title: "Plantando nuestro árbol",
    icon: "fas fa-seedling",
    content: {
      text: "Plantar ese árbol juntos simbolizó tanto para nosotros. Algo que crecerá con el tiempo, que necesita cuidado y atención, que echará raíces profundas... igual que nuestro amor. Vendremos a verlo crecer por muchos años.",
      images: ["images/tree-planting.jpg"],
      emoji: "🌱",
    },
    type: "symbolic",
  },
  {
    id: 24,
    date: "12 de Mayo, 2025",
    title: "Un año juntos",
    icon: "fas fa-birthday-cake",
    content: {
      text: "Hoy celebramos un año de risas, aprendizajes, aventuras y amor. El primero de muchos. Cada día contigo es un regalo y no puedo esperar para seguir escribiendo nuestra historia juntos. Te amo más que ayer y menos que mañana.",
      images: ["images/anniversary.jpg", "images/anniversary-2.jpg"],
      audio: "audio/year-together.mp3",
      emoji: "🎂",
    },
    type: "anniversary",
  },
];

// Mapeo de tipos de eventos con colores
const typeColors = {
  love: "#ff7b9c",
  date: "#ff9a7b",
  trip: "#7bc9ff",
  family: "#7bff9a",
  entertainment: "#c97bff",
  anniversary: "#ffda7b",
  home: "#7bd5ff",
  celebration: "#ffaa55",
  achievement: "#55c7ff",
  spontaneous: "#d67bff",
  symbolic: "#97db5e",
};

// Exportar los datos para que puedan ser importados desde app2.js
export { timelineData, typeColors };
